# House Price Prediction : Data Preprocessing and Feature Engineering

### Importing required libraries

In [296]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

### Load Datasets

In [297]:
dftrain = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train_len = train.shape[0]
print("Full train dataset shape is {}".format(train.shape))
test["SalePrice"] = np.nan

Full train dataset shape is (1460, 81)

In [298]:
train.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

### Combine train and test dataset

In [299]:
full = pd.concat([train, test], ignore_index=True)

### Drop Irrelevant Columns

In [300]:
full.drop(columns=["Id"], inplace=True)
full.head(5)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [301]:
full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     2919 non-null   int64
 1   MSZoning       2915 non-null   object
 2   LotFrontage    2433 non-null   float64
 3   LotArea        2919 non-null   int64
 4   Street         2919 non-null   object
 5   Alley          198 non-null    object
 6   LotShape       2919 non-null   object
 7   LandContour    2919 non-null   object
 8   Utilities      2917 non-null   object
 9   LotConfig      2919 non-null   object
 10  LandSlope      2919 non-null   object
 11  Neighborhood   2919 non-null   object
 12  Condition1     2919 non-null   object
 13  Condition2     2919 non-null   object
 14  BldgType       2919 non-null   object
 15  HouseStyle     2919 non-null   object
 16  OverallQual    2919 non-null   int64
 17  OverallCond    2919 non-null   int64
 18  YearBuilt      2919 non-null   int64
 19  YearRemodAdd   2919 non-null   int64
 20  RoofStyle      2919 non-null   object
 21  RoofMatl       2919 non-null   object
 22  Exterior1st    2918 non-null   object
 23  Exterior2nd    2918 non-null   object
 24  MasVnrType     1153 non-null   object
 25  MasVnrArea     2896 non-null   float64
 26  ExterQual      2919 non-null   object
 27  ExterCond      2919 non-null   object
 28  Foundation     2919 non-null   object
 29  BsmtQual       2838 non-null   object
 30  BsmtCond       2837 non-null   object
 31  BsmtExposure   2837 non-null   object
 32  BsmtFinType1   2840 non-null   object
 33  BsmtFinSF1     2918 non-null   float64
 34  BsmtFinType2   2839 non-null   object
 35  BsmtFinSF2     2918 non-null   float64
 36  BsmtUnfSF      2918 non-null   float64
 37  TotalBsmtSF    2918 non-null   float64
 38  Heating        2919 non-null   object
 39  HeatingQC      2919 non-null   object
 40  CentralAir     2919 non-null   object
 41  Electrical     2918 non-null   object
 42  1stFlrSF       2919 non-null   int64
 43  2ndFlrSF       2919 non-null   int64
 44  LowQualFinSF   2919 non-null   int64
 45  GrLivArea      2919 non-null   int64
 46  BsmtFullBath   2917 non-null   float64
 47  BsmtHalfBath   2917 non-null   float64
 48  FullBath       2919 non-null   int64
 49  HalfBath       2919 non-null   int64
 50  BedroomAbvGr   2919 non-null   int64
 51  KitchenAbvGr   2919 non-null   int64
 52  KitchenQual    2918 non-null   object
 53  TotRmsAbvGrd   2919 non-null   int64
 54  Functional     2917 non-null   object
 55  Fireplaces     2919 non-null   int64
 56  FireplaceQu    1499 non-null   object
 57  GarageType     2762 non-null   object
 58  GarageYrBlt    2760 non-null   float64
 59  GarageFinish   2760 non-null   object
 60  GarageCars     2918 non-null   float64
 61  GarageArea     2918 non-null   float64
 62  GarageQual     2760 non-null   object
 63  GarageCond     2760 non-null   object
 64  PavedDrive     2919 non-null   object
 65  WoodDeckSF     2919 non-null   int64
 66  OpenPorchSF    2919 non-null   int64
 67  EnclosedPorch  2919 non-null   int64
 68  3SsnPorch      2919 non-null   int64
 69  ScreenPorch    2919 non-null   int64
 70  PoolArea       2919 non-null   int64
 71  PoolQC         10 non-null     object
 72  Fence          571 non-null    object
 73  MiscFeature    105 non-null    object
 74  MiscVal        2919 non-null   int64
 75  MoSold         2919 non-null   int64
 76  YrSold         2919 non-null   int64
 77  SaleType       2918 non-null   object
 78  SaleCondition  2919 non-null   object
 79  SalePrice      1460 non-null   float64
dtypes: float64(12), int64(25), object(43)
memory usage: 1.8+ MB

In [302]:
full.describe().T

,count,mean,std,min,25%,50%,75%,max
MSSubClass,2919.0,57.137718,42.517628,20.0,20.0,50.0,70.0,190.0
LotFrontage,2433.0,69.305795,23.344905,21.0,59.0,68.0,80.0,313.0
LotArea,2919.0,10168.114080,7886.996359,1300.0,7478.0,9453.0,11570.0,215245.0
OverallQual,2919.0,6.089072,1.409947,1.0,5.0,6.0,7.0,10.0
OverallCond,2919.0,5.564577,1.113131,1.0,5.0,5.0,6.0,9.0
YearBuilt,2919.0,1971.312778,30.291442,1872.0,1953.5,1973.0,2001.0,2010.0
YearRemodAdd,2919.0,1984.264474,20.894344,1950.0,1965.0,1993.0,2004.0,2010.0
MasVnrArea,2896.0,102.201312,179.334253,0.0,0.0,0.0,164.0,1600.0
BsmtFinSF1,2918.0,441.423235,455.610826,0.0,0.0,368.5,733.0,5644.0
BsmtFinSF2,2918.0,49.582248,169.205611,0.0,0.0,0.0,0.0,1526.0
BsmtUnfSF,2918.0,560.772104,439.543659,0.0,220.0,467.0,805.5,2336.0
TotalBsmtSF,2918.0,1051.777587,440.766258,0.0,793.0,989.5,1302.0,6110.0
1stFlrSF,2919.0,1159.581706,392.362079,334.0,876.0,1082.0,1387.5,5095.0
2ndFlrSF,2919.0,336.483727,428.701456,0.0,0.0,0.0,704.0,2065.0
LowQualFinSF,2919.0,4.694416,46.396825,0.0,0.0,0.0,0.0,1064.0
GrLivArea,2919.0,1500.759849,506.051045,334.0,1126.0,1444.0,1743.5,5642.0
BsmtFullBath,2917.0,0.429894,0.524736,0.0,0.0,0.0,1.0,3.0
BsmtHalfBath,2917.0,0.061364,0.245687,0.0,0.0,0.0,0.0,2.0
FullBath,2919.0,1.568003,0.552969,0.0,1.0,2.0,2.0,4.0
HalfBath,2919.0,0.380267,0.502872,0.0,0.0,0.0,1.0,2.0
BedroomAbvGr,2919.0,2.860226,0.822693,0.0,2.0,3.0,3.0,8.0
KitchenAbvGr,2919.0,1.044536,0.214462,0.0,1.0,1.0,1.0,3.0
TotRmsAbvGrd,2919.0,6.451524,1.569379,2.0,5.0,6.0,7.0,15.0
Fireplaces,2919.0,0.597122,0.646129,0.0,0.0,1.0,1.0,4.0
GarageYrBlt,2760.0,1978.113406,25.574285,1895.0,1960.0,1979.0,2002.0,2207.0
GarageCars,2918.0,1.766621,0.761624,0.0,1.0,2.0,2.0,5.0
GarageArea,2918.0,472.874572,215.394815,0.0,320.0,480.0,576.0,1488.0
WoodDeckSF,2919.0,93.709832,126.526589,0.0,0.0,0.0,168.0,1424.0
OpenPorchSF,2919.0,47.486811,67.575493,0.0,0.0,26.0,70.0,742.0
EnclosedPorch,2919.0,23.098321,64.244246,0.0,0.0,0.0,0.0,1012.0
3SsnPorch,2919.0,2.602261,25.188169,0.0,0.0,0.0,0.0,508.0
ScreenPorch,2919.0,16.062350,56.184365,0.0,0.0,0.0,0.0,576.0
PoolArea,2919.0,2.251799,35.663946,0.0,0.0,0.0,0.0,800.0
MiscVal,2919.0,50.825968,567.402211,0.0,0.0,0.0,0.0,17000.0
MoSold,2919.0,6.213087,2.714762,1.0,4.0,6.0,8.0,12.0
YrSold,2919.0,2007.792737,1.314964,2006.0,2007.0,2008.0,2009.0,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,129975.0,163000.0,214000.0,755000.0

### Missing values to be handled

In [303]:
full.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          2909
MiscFeature     2814
Alley           2721
Fence           2348
MasVnrType      1766
SalePrice       1459
FireplaceQu     1420
LotFrontage      486
GarageFinish     159
GarageQual       159
GarageCond       159
GarageYrBlt      159
GarageType       157
BsmtCond          82
BsmtExposure      82
BsmtQual          81
BsmtFinType2      80
BsmtFinType1      79
MasVnrArea        23
MSZoning           4
dtype: int64

### Handle missing values (using domain logic)

In [304]:
na_none_cols = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu',
                'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
                'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
                'MasVnrType']
for col in na_none_cols:
    full[col] = full[col].fillna("None")

na_zero_cols = ['GarageYrBlt', 'GarageArea', 'GarageCars',
                'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'MasVnrArea']
for col in na_zero_cols:
    full[col] = full[col].fillna(0)

In [305]:
for col in full.columns:
    if full[col].isna().sum() > 0:
        if full[col].dtype == "object":
            full[col] = full[col].fillna(full[col].mode()[0])
        else:
            full[col] = full[col].fillna(full[col].median())

In [306]:
full.isnull().sum().sort_values(ascending=False).head(20)

MSSubClass      0
MSZoning        0
GarageYrBlt     0
GarageType      0
FireplaceQu     0
Fireplaces      0
Functional      0
TotRmsAbvGrd    0
KitchenQual     0
KitchenAbvGr    0
BedroomAbvGr    0
HalfBath        0
FullBath        0
BsmtHalfBath    0
BsmtFullBath    0
GrLivArea       0
LowQualFinSF    0
2ndFlrSF        0
1stFlrSF        0
GarageFinish    0
dtype: int64

### Feature Engineering

In [307]:
full['TotalSF'] = full['TotalBsmtSF'] + full['1stFlrSF'] + full['2ndFlrSF']
full['TotalBathrooms'] = (full['FullBath'] + 0.5 * full['HalfBath'] +
                          full['BsmtFullBath'] + 0.5 * full['BsmtHalfBath'])
full['Age'] = full['YrSold'] - full['YearBuilt']
full['RemodAge'] = full['YrSold'] - full['YearRemodAdd']
full['HasPool'] = (full['PoolArea'] > 0).astype(int)
full['HasGarage'] = (full['GarageArea'] > 0).astype(int)
full['HasFireplace'] = (full['Fireplaces'] > 0).astype(int)
full['HasBsmt'] = (full['TotalBsmtSF'] > 0).astype(int)
cols = ['TotalSF', 'TotalBathrooms', 'Age', 'RemodAge', 
                   'HasPool', 'HasGarage', 'HasFireplace', 'HasBsmt']
display(full[cols].head())

,TotalSF,TotalBathrooms,Age,RemodAge,HasPool,HasGarage,HasFireplace,HasBsmt
0,2566.0,3.5,5,5,0,1,0,1
1,2524.0,2.5,31,31,0,1,1,1
2,2706.0,3.5,7,6,0,1,1,1
3,2473.0,2.0,91,36,0,1,1,1
4,3343.0,3.5,8,8,0,1,1,1

### Ordinal and Label Encoding

In [308]:
qual_map = {'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'None': 0}
for col in ['ExterQual', 'KitchenQual', 'FireplaceQu', 'BsmtQual', 'BsmtCond', 
            'GarageQual', 'GarageCond', 'HeatingQC']:
    full[col] = full[col].map(qual_map)
ordinal_cols = ['ExterQual', 'KitchenQual', 'FireplaceQu', 'BsmtQual', 
                'BsmtCond', 'GarageQual', 'GarageCond', 'HeatingQC']
display(full[ordinal_cols].head())

,ExterQual,KitchenQual,FireplaceQu,BsmtQual,BsmtCond,GarageQual,GarageCond,HeatingQC
0,4,4,0,4,3,3,3,5
1,3,3,3,4,3,3,3,5
2,4,4,3,4,3,3,3,5
3,3,4,4,3,4,3,3,4
4,4,4,3,4,3,3,3,5

In [309]:
label_cols = full.select_dtypes(include='object').columns
le = LabelEncoder()
for col in label_cols:
    full[col] = le.fit_transform(full[col])
display(full[label_cols[:8]].head())

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope
0,3,1,1,3,3,0,4,0
1,3,1,1,3,3,0,2,0
2,3,1,1,0,3,0,4,0
3,3,1,1,0,3,0,0,0
4,3,1,1,0,3,0,2,0

### Split the full cleaned dataset back into train and test sets and save in csv files

In [310]:
processed_train = full.iloc[:train_len, :]
processed_test = full.iloc[train_len:, :].drop("SalePrice", axis=1)

processed_train.to_csv("processed_train.csv", index=False)
processed_test.to_csv("processed_test.csv", index=False)